/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:f792874a-4fd2-4572-8207-692bc829aa2d",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_xd2UNbLy4",
    "aws_user_pools_web_client_id": "51nv9b5pokilii0itn95sjm16v",
    "oauth": {}
};


export default awsmobile;
